### ISSUE TITLE
Removing rancher-monitoring app leaves cattle-monitoring-system namespace in place

### ISSUE THREAD

**Issue by thehejik** [rancher/charts#1038]
When I deleted `rancher-monitoring` and `rancher-monitoring-crd` apps the used namespace `cattle-monitoring-system` remained in place.

This is a bit problematic when user is trying to redeploy the `rancher-monitoring` chart once again, and the namespace exists already, the project dropdown is not available anymore in Cluster Explorer.

Versions info: Installing `rancher-monitoring-9.4.204-rc04` from https://git.rancher.io/charts branch `dev-v2.5` on `rancher:2.5.7` on windows cluster with kubernetes `v1.20.4-rancher1-1`.

Attempt to re-deploy monitoring-rancher (namespace `cattle-monitoring-system` already exists):
![monitoring-ns-exists](https://user-images.githubusercontent.com/12828077/111492493-00bbe200-873d-11eb-8512-d40e647ba744.png)

VS

Fresh deployment of the monitoring-rancher (or re-deploy after manual deletion of `cattle-monitoring-system` namespace):
![monitoring-ns-doesntexist](https://user-images.githubusercontent.com/12828077/111492522-074a5980-873d-11eb-9dc6-c1dbc9489767.png)

**Comment by sowmyav27** [comment]
Not an issue and a dup of https://github.com/rancher/rancher/issues/28864

**Comment by jiaqiluo** [comment]
@thehejik  If you want to fully clean up the monitoring app and reinstall it, the workaround is
- delete all secrets in the namespace `cattle-monitoring-system` first
- then delete the namespace itself

**Comment by louie007** [comment]
Delete custom apiservice `v1beta1.custom.metrics.k8s.io` will fix this issue.

```shell
$ kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n cattle-monitoring-system
error: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request

$ kubectl get APIService v1beta1.custom.metrics.k8s.io
NAME                            SERVICE                                                          AVAILABLE                 AGE
v1beta1.custom.metrics.k8s.io   cattle-monitoring-system/rancher-monitoring-prometheus-adapter   False (ServiceNotFound)   124m

$ kubectl describe apiservice v1beta1.custom.metrics.k8s.io
Name:         v1beta1.custom.metrics.k8s.io
Namespace:
Kind:         APIService ...........

$ kubectl delete apiservice v1beta1.custom.metrics.k8s.io
apiservice.apiregistration.k8s.io "v1beta1.custom.metrics.k8s.io" deleted
```
