### ISSUE TITLE
Launch `vault-operator` app error

### ISSUE THREAD

**Issue by rootwuj** [rancher/charts#113]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Deploy the `vault-operator `app using the default parameters in the catalog page.

**Result:**
 It will report:
 ```
 Failed to install app vault-operator. Error: validation failed: unable to recognize "": no matches for kind "VaultService" in version "vault.security.coreos.com/v1alpha1"
 ```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher v2.0.10/v2.1.5/2.2
- Installation option (single install/HA): single

**Comment by Dan-Coleman** [comment]
Also experiencing the same issue with my Rancher instance

**Comment by guangbochen** [comment]
@rootwuj can u please validate it with the latest version v0.1.2, thanks.

**Comment by rootwuj** [comment]
Version: master 2.2 (2/20/19) Image ID: cdd98a0abb92
This version of vault-operator (v0.1.2) can be deployed successfully and run successfully.
Confirmed fixed.
