### ISSUE TITLE
[nfs-provisioner/v0.1.1] Pod cannot create file in NFS PV

### ISSUE THREAD

**Issue by Dremor** [rancher/charts#13]
When mounting an NFS PVC, it is not possible to create any file of folder inside the mounted filesystem.

I reported the issue to the upstream project here: https://github.com/kubernetes-incubator/external-storage/issues/774

It seems that the ganesha nfs server isn't yet fully compatible with NFS 4.2: https://github.com/nfs-ganesha/nfs-ganesha/issues/192

Thus, you have to manually force the mount NFS version to the "4.1" version or lower, as suggested by this comment: https://github.com/kubernetes-incubator/external-storage/issues/223#issuecomment-344972640

I've a working prototype of this fix here: https://gitlab.com/egeorget/rancher2-charts/tree/devel/nfs-provisioner

**Comment by Dremor** [comment]
This won't work. I tried the same on my chart.
- mountOption is an array
- mountOption like this seem to be ignored by nfs mount.

**Comment by Dremor** [comment]
I investigated this a bit more the upstream project. The option "mountOptions" isn't even taken into account in the current option parser, but a "mountOptions" option into the "Parameters" list is taken into account.

I'll try to upstream a patch in order to resolve this.

**Comment by guangbochen** [comment]
close for inactive.
