### ISSUE TITLE
Longhorn 1.1.2 is not available on cluster explorer

### ISSUE THREAD

**Issue by gricuk** [rancher/charts#1464]
Hi, could you please explain why longhorn 1.1.2 is not available on Cluster explorer but available on Cluster Manager
Cluster explorer:
<img width="1544" alt="Screen Shot 2021-09-03 at 9 06 04 PM" src="https://user-images.githubusercontent.com/9693387/132048723-e47178bf-ce86-4263-a3ef-137d725b3579.png">

Cluster Manager:
<img width="1475" alt="Screen Shot 2021-09-03 at 9 06 50 PM" src="https://user-images.githubusercontent.com/9693387/132048791-736d91aa-605a-4580-bbe7-aa69cbcbb621.png">

**rancher version: 2.5.9**

**Comment by UnstoppableMango** [comment]
v1.2.0 has recently released as well https://github.com/longhorn/longhorn/releases/tag/v1.2.0

**Comment by gricuk** [comment]
But what about 1.1.2? why this version still unavailable on Cluster Explorer?(see my first screen)

> v1.2.0 has recently released as well https://github.com/longhorn/longhorn/releases/tag/v1.2.0

**Comment by innobead** [comment]
Please refer to https://github.com/rancher/charts/issues/1352#issuecomment-887999551.

Simply said, Longhorn release for cluster explorer is coupled with rancher releases for some reasons like air gap, security, etc. So in the latest 2.6.0, 1.1.2 is available but for 2.5.*, u need to wait for 2.5.10.

But for cluster manager, there is no this coupling, so longhorn versions will be available soon after the corresponding chart PRs merged.

**Comment by cbron** [comment]
It's available now.
