### ISSUE TITLE
Creating a helm repo for charts

### ISSUE THREAD

**Issue by botzill** [rancher/charts#148]
Hi.

Is there a way to install these charts from a repo? Every time there is a new update I have to copy the files which is not convenient at all. 

Thx a lot!

**Comment by guangbochen** [comment]
Rancher support git type helm repo so you can install directly from its Catalog Apps page, or you can host this repo by your own either using https://github.com/helm/chartmuseum or some based on https://github.com/helm/chartmuseum.
