### ISSUE TITLE
Charts Maintenance Ticket - Tracking the decommissioning of charts repo.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/charts#1594]
This is just a tracking ticket that I wanted to put into the charts repo as a tracking ticket to help monitor the decommissioning of the charts repo, for example we need to have someone assigned to put the max version into charts, etc.

**Comment by deniseschannon** [comment]
I believe this was taken care of other changes as we are no longer allowing new installs of charts as of k8s 1.22.
