### ISSUE TITLE
vSphere CPI has incorrect tolerations for etcd

### ISSUE THREAD

**Issue by mattstocum** [rancher/charts#1645]
In the vSphere CPI version 100.1.0up1.0.100 the toleration for etcd is [currently](https://github.com/rancher/charts/blob/dd20f254d5dd6688dcc4ea480107d02e03420796/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.1.0%2Bup1.0.100/templates/daemonset.yaml#L72):
```
        - key: node-role.kubernetes.io/etcd
          effect: NoSchedule
          value: "true"
```

but Rancher is tainting the etcd nodes with NoExecute, not NoSchedule. I believe the line should read:
```
        - key: node-role.kubernetes.io/etcd
          effect: NoExecute
          value: "true"
```

**Comment by mattstocum** [comment]
The CSI has the same issue at https://github.com/rancher/charts/blob/54172f8a318a5aa6c043f24aacbf2180812dea67/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0%2Bup2.3.0/templates/controller/deployment.yaml#L60

**Comment by braunsonm** [comment]
Whoops I duplicated this issue here: https://github.com/rancher/charts/issues/1681

**Comment by PennyScissors** [comment]
@mattstocum Thanks for submitting this issue. As @braunsonm commented, a duplicate issue has been submitted to the rancher/rancher repository. For this reason I'm going to close this issue as I've already added a comment with a workaround in the issue he submitted (see [this](https://github.com/rancher/rancher/issues/36081#issuecomment-1007806219) comment).
