### ISSUE TITLE
Upgrade grafana helm chart to latest version

### ISSUE THREAD

**Issue by LockedThread** [rancher/charts#1695]
I don't think much needs to be said but if you want to be able to use loki and tempo you need the latest versions of grafana to make all of the newer functions work.

https://grafana.com/docs/tempo/latest/getting-started/tempo-in-grafana/#log-search

**Comment by cm0s** [comment]
Grafana 8 has been released in June 2021. It's about time to upgrade.

I need version 8 in order to use the new united alerting manager of Grafana 8

**Comment by LockedThread** [comment]
> Grafana 8 has been released in June 2021. It's about time to upgrade.
> 
> I need version 8 in order to use the new united alerting manager of Grafana 8

Definitely agree.

**Comment by michbeck100** [comment]
Is there any progress on this?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Push, would be nice to see *at least* Grafana 8!

**Comment by LockedThread** [comment]
I've spoke with some Rancher employees a couple months back and they had no interest in pursuing this at all. Honestly, I have given up on Rancher entirely as it has brought me more problems than I had hoped for. If you want Grafana 8 just use the bitnami chart for it.

**Comment by aiyengar2** [comment]
@LockedThread this will be addressed in https://github.com/rancher/rancher/issues/37778 which will be shipped in the Q1 2.6 release of Rancher.

FWIW: the primary reason for delaying this upgrade had nothing do do with having "no interest in pursuing this"... as mentioned in https://github.com/rancher/charts/issues/1695#issuecomment-1118724133, the change in licensing was a cause for concern that has since been resolved.

**Comment by aiyengar2** [comment]
Closing this out in favor of https://github.com/rancher/rancher/issues/37778

**Comment by LockedThread** [comment]
> @LockedThread this will be addressed in https://github.com/rancher/rancher/issues/37778 which will be shipped in the Q1 2.6 release of Rancher.
> 
> 
> 
> FWIW: the primary reason for delaying this upgrade had nothing do do with having "no interest in pursuing this"... as mentioned in https://github.com/rancher/charts/issues/1695#issuecomment-1118724133, the change in licensing was a cause for concern that has since been resolved.

I was just paraphrasing what was told to me by a staff member in the slack.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Does this mean that grafana 8 is included now? Is there already a release where it's included?
