### ISSUE TITLE
[Monitoring V2] KubePodCrashLooping alert is incorrect

### ISSUE THREAD

**Issue by boxboatmatt** [rancher/charts#1780]
Rancher-monitoring is currently broken, as the below mentioned PR is not included in the current ruleset. If a pod is in a crash loop you will never be alerted.

https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/674/files

**Comment by aiyengar2** [comment]
Should be fixed in the chart that was rebased in https://github.com/rancher/rancher/issues/37778.

Thanks for the issue @boxboatmatt! Closing in favor of the rebase issue
