### ISSUE TITLE
cert-manager upgrade to version 8

### ISSUE THREAD

**Issue by daxmc99** [rancher/charts#179]
I was able to install cert-manager version 8 with these steps. 

1.     Add https://charts.jetstack.io to global catalogs
2.     Enter into the system project
3.     Install cert-manager v8 into the 'kube-system' namespace.

We should see about creating a questions.yaml file for this chart to allow for installation into 'kube-system' more easily.

**Comment by tlitovsk** [comment]
Hi.

Let's encrypt plans to block all cert managers less than version 8 starting November 1.
Can we please have an updated chart in the curated library.

Best Regards

**Comment by cesarandreslopez** [comment]
This chart needs an upgrade soon, please. From a Let's encrypt email:

"we plan to start blocking all traffic from cert-manager versions less than 0.8.0 (the 
current semver minor release), as of November 1, 2019. Please upgrade 
all of your cert-manager instances before then."

**Comment by guangbochen** [comment]
Yes, we have planned to upgrade those curated charts to align with Rancher 2.3 releases(mid-sep.),  will add a reply to this question once it is released, thanks.

**Comment by dramich** [comment]
The fix for this needs to ensure it's getting deployed properly when moving to version 9. Per the [upgrade docs](https://docs.cert-manager.io/en/latest/tasks/upgrading/upgrading-0.8-0.9.html) the correct way to do that is to delete the current deployment and re-deploy. QA work for this would need to validate this step is being done.

**Comment by amagura** [comment]
@guangbochen The Rancher 2.3 release came and went--do you have any update on when this chart will be updated to version 0.8.0 or 0.9.0?  November 1st is little more than a week away!

**Comment by dramich** [comment]
@amagura see the [forum post](https://forums.rancher.com/t/update-on-cert-manager-application-in-the-catalog/15598)

**Comment by amagura** [comment]
@dramich This doesn't work for my setup.  We're not using helm and are entirely dependent on Rancher's app catalog.  Also I took some time and looked at the code for cert-manager; there's a branch that has a `v0.9.1` directory in it--is that just empty then?  Are y'all not going to add support for installing this via Rancher's app catalog ever?  @guangbochen

**Comment by dramich** [comment]
@amagura from the forum post:

> Jetstack is rapidly approaching a 1.0 release of cert-manager, after which the pace of changes will hopefully subside. When we’re able to ensure that your experience with cert-manager in the App Catalog is easy and painless, we’ll look into bringing it back into the App Catalog.
