### ISSUE TITLE
Upgrade rancher-monitoring / Prometheus Operator to 0.55.0

### ISSUE THREAD

**Issue by FlxPeters** [rancher/charts#1832]
Rancher has packaged Prometheus Operator in version 0.50.0 in the `rancher-monitoring` chart (release-2.6).
The operator version was released in Aug 2021. Since this time the Prometheus ecosystem has introduced relevant enhancements like time intervals and the matcher syntax in Alertmanager for much more flexible alerting routes. 

These improvements are not usable as a Rancher user because the Operator does not recognize this features and throws an error for a invalid configuration. We should update the operator Chart to at least version 0.55.0 or newer. 

This may also implies changes to the Rancher UI because of new fields in the CRDs. 

Some questions related to this issue:
* Is there any process to trigger such changes or is this already a task that rancher has planned for 2.7?
*  What are the general guidelines for version upgrades of packaged operators? 

Thanks for your effort and keep up the good work.

**Comment by danragnar** [comment]
Would also like to see this. The shipped alertmanager version (0.22.2) seems to support the new route matchers syntax while the operator version does not, which is really confusing. I think you would need to go to operator version 0.52 to get support for that.

**Comment by FlxPeters** [comment]
Any news on this issue? Having rancher integrated tools is nice, but they should follow the upstream operators.

**Comment by aiyengar2** [comment]
Should be at `v0.59.1` after https://github.com/rancher/rancher/issues/37778 is merged.

Closing in favor of the other issue.
