### ISSUE TITLE
[rancher-monitoring/v100.1.2+up19.0.3] deprecated etcd db size metric still being used

### ISSUE THREAD

**Issue by AshleyDumaine** [rancher/charts#1845]
As of etcd v3.5, `etcd_debugging_mvcc_db_total_size_in_bytes` is [deprecated and removed](https://etcd.io/docs/v3.4/upgrades/upgrade_3_5/) in favor of `etcd_mvcc_db_total_size_in_bytes`. 

There are still 2 lingering references to the deprecated metric in the latest version of rancher-monitoring:
```
files/rancher/k8s/rancher-etcd-nodes.json
177:          "expr": "sum(etcd_debugging_mvcc_db_total_size_in_bytes) by (instance)",

files/rancher/k8s/rancher-etcd.json
169:          "expr": "sum(etcd_debugging_mvcc_db_total_size_in_bytes)",
```

If `debugging_` is removed from above, Rancher will correctly show etcd DB size metrics in the cluster dashboard:
![Screen Shot 2022-04-05 at 3 11 30 PM](https://user-images.githubusercontent.com/5779804/161831674-1f4338f9-acf5-4286-bf59-285a90544fb3.jpg)

**Comment by aiyengar2** [comment]
Fixed in latest chart that will be tested in https://github.com/rancher/rancher/issues/37778. Will add a note to the main issue.

Closing in favor of the main issue.
