### ISSUE TITLE
`rancher-monitoring:100.1.0+up19.0.3` - Upgrade grafana

### ISSUE THREAD

**Issue by r65535** [rancher/charts#1933]
The grafana chart used in rancher-monitoring is pinned to 7.5

Could this be upgraded to 8+? It looks like grafana 9 is also in beta

**Comment by PrettySolution** [comment]
Hello, 

I am interested in the new version of Grafana. 
Please help to address

**Comment by LinAnt** [comment]
Grafana 9.1.x is out, I tested bumping the current version in our playground cluster, but proxying traffic fails with 404.

**Comment by LinAnt** [comment]
I tried to find any info on how Grafana Labs supports releases, and with 9.x being latest I suspect 7.x is EOL.

https://community.grafana.com/t/grafana-7-reached-eol-after-grafana-9-was-released/67814

**Comment by hbouaziz** [comment]
Hello ! I tried the latest chart version of Grafana (image version v9.1.x) to work with Loki project 
And I got some rancher proxy error. 
Port forwarding works fine, using ingress too but when I try to access via Rancher I got 404 Error Page Unauthorized 
Downgrading the version to 7.5.11 solved the issue but it's not the best of solutions yet.
Thankyou!

**Comment by strowi** [comment]
Also interested in an update since Grafana-7.x Version has this annoying Bug when typing metrics queries, which makes this part unusable.

**Comment by aiyengar2** [comment]
Addressed in https://github.com/rancher/rancher/issues/37778, we upgraded to 9.x.x
