### ISSUE TITLE
vsphere-cpi-cloud-controller-manager DaemonSet deploying to all nodes rather than just control plane

### ISSUE THREAD

**Issue by inichols** [rancher/charts#1977]
After updating to use the newest CPI chart, it was found that it ran on all the nodes rather than just the Control Plane like previously. It was found that a NotIn Windows block was found. After removing that, and redeploying it worked as expected.

Here we see there are 3 separate matchExpressions blocks.
https://github.com/rancher/charts/blob/fb4f73335fda484d517a946581e788189745787f/charts/rancher-vsphere-cpi/100.3.0%2Bup1.2.1/templates/daemonset.yaml#L31-L51

The information in this comment looks to show that this means these are all implemented as OR statements rather than AND.
https://github.com/kubernetes/kubernetes/pull/70394#issuecomment-434127780

From my understanding, I believe this setup is what would be required, as it sets a match for both RKE1 Control Plane and not Windows, OR RKE2 Control Plane and not Windows.

>           
           - matchExpressions:
              # RKE node selector label
              - key: node-role.kubernetes.io/controlplane
                operator: In
                values:
                - "true"
              - key: kubernetes.io/os
                operator: NotIn
                values:
                - "windows"
            - matchExpressions:
              # RKE2 node selector label
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                - "true"
              - key: kubernetes.io/os
                operator: NotIn
                values:
                - "windows"

SURE-5315

**Comment by inichols** [comment]
@phillipsj

**Comment by fabiorauber** [comment]
Just bumped into that, when updating my vSphere CPI chart.

**Comment by snasovich** [comment]
To be fixed in `rancher/vsphere-charts` as part of https://github.com/rancher/vsphere-charts/issues/46 before brought into the charts here.

**Comment by cwayne18** [comment]
@slickwarren is this resolved?  All the linked PR's seem to. be merged, I'm wondering if we need to pull in the charts from `rancher/vsphere-charts` or if maybe we just missed closing this one out?

**Comment by slickwarren** [comment]
this should be fixed, I can add it to my queue and test.

**Comment by slickwarren** [comment]
tested on v2.7.7-rc4 with chart version `rancher-vsphere-cpi:1.5.100` this issue is no longer seen, and the chart's daemonset node scheduling has been updated appropriately:
![Screen Shot 2023-09-25 at 11 25 27 AM](https://github.com/rancher/charts/assets/16691014/c1b2f8b4-52f1-48e9-96c0-d7c4e5668359)
