### ISSUE TITLE
helm delete does not clean admin password and rancher server url , even  with  --purege 

### ISSUE THREAD

**Issue by wuenping** [rancher/charts#198]
I use helm  delete --purege   then  reinstall

rancher ui skip  setup admin password and Rancher Server Url

how to clean ?  If I open first login  and close the page right now  without any settings 

terrible！

**Comment by guangbochen** [comment]
Google is your friend https://rancher.com/docs/rancher/v2.x/en/faq/technical/, and btw you should ask those type of questions in [rancher/rancher](https://github.com/rancher/rancher), this is Rancher's catalog charts repo.

Lastly, this is not terrible! you should be able to login with your previous password or if you don't set the first-time login password the server will set a default one for your for security purpose.
