### ISSUE TITLE
vault-operator documentation missing essential info

### ISSUE THREAD

**Issue by erSitzt** [rancher/charts#202]
Hi,

there is a nice sentence in the coreos documentation that helps to understand whats happening after `vault operator init` and how the unsealing has to be done...

> The first node that is unsealed in a multi-node Vault cluster will become the active node. The active node holds the leader election lock. The other unsealed nodes become standby.

It would be nice to have that info in the UI of Rancher when deploying the App/Chart, because i got stuck for some time not knowing i had to run the port-forward / unseal commands twice...

**Comment by erSitzt** [comment]
When the second node is unsealed it enters `Standby Mode`, but in Rancher the workload will look like it has a problem... is this intentional ?
![image](https://user-images.githubusercontent.com/1625376/62537665-46ba7f80-b851-11e9-8fd0-a8d4526f0a65.png)

The app is listed as `Active` btw.
![image](https://user-images.githubusercontent.com/1625376/62537714-63ef4e00-b851-11e9-8ab1-cef80ead81f6.png)

**Comment by guangbochen** [comment]
we do have one in our `Notes.txt`, but this apparently is not as obvious as have them in the app-readme section, will consider to add it in both sections in the coming new version, thanks.
![image](https://user-images.githubusercontent.com/4569037/62615661-45b44b80-b940-11e9-883e-35bd6ad6cc63.png)

**Comment by erSitzt** [comment]
Yeah there is a Notes.txt, but it does not mention that the second node needs to be unsealed too and that it will stay in a state that looks like a failed pod in the rancher ui.

Maybe just take their description and add those parts of information

**Comment by guangbochen** [comment]
updated in https://github.com/rancher/charts/tree/master/charts/vault-operator/v0.1.3
