### ISSUE TITLE
Rancher Monitoring - connection refused error from pushprox-ingress-nginx-client

### ISSUE THREAD

**Issue by pmackey2** [rancher/charts#2042]
I've run into an issue deploying the Monitoring chart into a newly provisioned RKE2 cluster. The chart successfully deploys, but the newly created Prometheus fails on its `rancher-monitoring-igress-nginx` target. It receives an HTTP 500 error from the `cattle-monitoring-system logs pushprox-ingress-nginx-client` pod.

I get:
```
[serviceMonitor/cattle-monitoring-system/rancher-monitoring-ingress-nginx/0 (0/1 up)
server returned HTTP status 500 Internal Server Error
```
And subsequently an alert in alert-manager:
```
warning | TargetDown | 100% of the ingress-nginx/pushprox-ingress-nginx-client targets in cattle-monitoring-system namespace are down.
```

## Versions
rancher-monitoring: 100.1.3+up19.0.3
rancher: 2.6.7
rke2: v1.23.9+rke2r1 (also reproduced on v1.22.12+rke2r1)

I've installed the chart from the Rancher UI with the default settings.

RKE2 has been deployed on top of Ubuntu Focal, not deployed from Rancher.

## Logs
The logs from the pod show that pushprox is getting a connection refused.

```
root@ip-172-31-42-125:~# kubectl -n cattle-monitoring-system logs pushprox-ingress-nginx-client-6bcd4f749d-r6tkq
level=info ts=2022-08-24T03:29:21.243Z caller=main.go:269 msg="URL and FQDN info" proxy_url=http://pushprox-ingress-nginx-proxy.cattle-monitoring-system.svc:8080/ fqdn=172.31.32.158
level=info ts=2022-08-24T03:30:17.212Z caller=main.go:232 msg="Got scrape request" scrape_id=c9b5c24f-f08c-4362-b6a4-c62757788e14 url=http://172.31.32.158:10254/metrics
level=error ts=2022-08-24T03:30:17.213Z caller=main.go:101 err="failed to scrape http://127.0.0.1:10254/metrics: Get \"http://127.0.0.1:10254/metrics\": dial tcp 127.0.0.1:10254: connect: connection refused"
level=info ts=2022-08-24T03:30:17.219Z caller=main.go:113 msg="Pushed failed scrape response"
```

**Comment by aiyengar2** [comment]
Probably addressed by https://github.com/rancher/rancher/issues/37778, there were a lot of changes that went into https://github.com/rancher/charts/commit/4d3bd3dc08e7e6ab7e251228a7b8b0d1ed64e2da.

**Comment by aiyengar2** [comment]
Closing in favor of the main issue
