### ISSUE TITLE
PromQL Query Issues in Rancher Monitoring

### ISSUE THREAD

**Issue by BryceTech122** [rancher/charts#2129]
Im experiancing isssues exactly as described in [QueryFields/Input fields are broken in the recent Chrome browser](https://github.com/grafana/grafana/issues/54535) with rancher monitoring 100.1.3+up19.0.3, any idea as to when there could be a patch?

**Comment by aiyengar2** [comment]
We've bumped Grafana in https://github.com/rancher/rancher/issues/37778, so we'll try to retest this there.

Closing this issue out in favor of the linked issue above; feel free to add any additional info on that ticket (or re-open if it still exists as an issue after that is merged).
