### ISSUE TITLE
Added values to yaml in Catalog Deployment (EFK-Stack) are not applied

### ISSUE THREAD

**Issue by chucky2305** [rancher/charts#22]
I want to deploy the efk stack (version 0.1.3).
Before i click on deploy, i want to change some values like so:

```
defaultImage: 'true'
elasticsearch.image.repository: docker.elastic.co/elasticsearch/elasticsearch-oss
elasticsearch.image.tag: 6.2.4
kibana.image.repository: docker.elastic.co/kibana/kibana-oss
kibana.image.tag: 6.2.4
fluent-bit.image.fluent_bit.repository: fluent/fluent-bit
fluent-bit.image.fluent_bit.tag: 0.13.0
elasticsearch.master.heapSize: 2g
elasticsearch.master.service.type: NodePort
elasticsearch.master.persistence.enabled: 'false'
elasticsearch.master.persistence.storageClass: ""
elasticsearch.master.persistence.size: 10Gi
kibana.ingress.enabled: 'true'
'kibana.ingress.hosts[0]': xip.io
fluent-bit.enabled: 'true'
fluent-bit.metrics.enabled: 'true'
```

The last value is not in the default (added by myself).

But it seems not to be applied. When i click on upgrade after the stack is deployed, i cannot see the new key/value pair.

Another reason why i think, that the new key/value is not applied is missing service that should be generated, as described here:
https://github.com/rancher/charts/blob/master/charts/efk/v0.1.3/charts/fluent-bit/templates/service.yaml

Any suggestions would be fine.

Thanks a lot in advance

**Comment by superseb** [comment]
This will be fixed in https://github.com/rancher/rancher/issues/14964

**Comment by superseb** [comment]
Fixed in https://github.com/rancher/rancher/issues/14964 and will be in next release.

**Comment by guangbochen** [comment]
resolved and closed.
