### ISSUE TITLE
mkfsParams and nodeSelector missing in charts/longhorn/101.1.0%2Bup1.3.2/templates/storageclass.yaml

### ISSUE THREAD

**Issue by valkenburg-prevue-ch** [rancher/charts#2318]
Comparing https://raw.githubusercontent.com/rancher/charts/dev-v2.7/charts/longhorn/101.1.0%2Bup1.3.2/templates/storageclass.yaml to https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/templates/storageclass.yaml, I find that the following lines are present upstream, and went missing in rancher's version:

```
\25a26,28
>       {{- if .Values.persistence.defaultMkfsParams }}
>       mkfsParams: "{{ .Values.persistence.defaultMkfsParams }}"
>       {{- end }}
38a42,44
>       {{- if .Values.persistence.defaultNodeSelector.enable }}
>       nodeSelector: "{{ .Values.persistence.defaultNodeSelector.selector }}"
>       {{- end }}
```

**Comment by innobead** [comment]
@valkenburg-prevue-ch this new parameter is just introduced to 1.4.0, so it's not supported in the previous versions including 1.3.2 

https://github.com/longhorn/longhorn/issues/4642

**Comment by innobead** [comment]
Closing first. @valkenburg-prevue-ch thanks for reporting and feel free to reopen if you still have any questions.
