### ISSUE TITLE
[BUG] Failed to upgrade rancher-istio from 102.2.0+up1.17.2 to 102.3.0-up1.18.2

### ISSUE THREAD

**Issue by skanakal** [rancher/charts#3149]
### Rancher Server Setup
- Rancher version: 2.7.4
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details:

### Information about the Cluster
- Kubernetes version:
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use?
- What is the version of Terraform in use?

### To Reproduce

Upstream cluster: Rancher 2.7.5 RKE1 (customer runs 2.7.4)
Deploy RKE2 cluster v1.25.13+rke2r1. Install Istio version 102.2.0+up1.17.2, default configuration using Cluster Tools. Try to upgrade to the  latest version 102.3.0+up1.18.2. The upgrade fails with error: 
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.volumes[4]): unknown field "[kubernetes.io/os](http://kubernetes.io/os)" in io.k8s.api.core.v1.Volume, ValidationError(Deployment.spec.template.spec.volumes[4]): unknown field "tolerations" in io.k8s.api.core.v1.Volume]

Deploy EKS  v1.24.16-eks-2d98532. Try to install version 102.3.0+up1.18.2 from Cluster Tools, default configuration. The installation fails with error:
helm install --namespace=istio-system --timeout=10m0s --values=/home/shell/helm/values-rancher-istio-102.3.0-up1.18.2.yaml --version=102.3.0+up1.18.2 --wait=true rancher-istio /home/shell/helm/rancher-istio-102.3.0-up1.18.2.tgz 2023-10-06T06:39:34.795219748Z Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.volumes[4]): unknown field "kubernetes.io/os" in io.k8s.api.core.v1.Volume, ValidationError(Deployment.spec.template.spec.volumes[4]): unknown field "tolerations" in io.k8s.api.core.v1.Volume]

### Actual Result

istio failed to upgrade/install

### Expected Result

istio should be upgraded/installed

**Comment by skanakal** [comment]
Inter ref: https://jira.suse.com/browse/SURE-7041

**Comment by rohitsakala** [comment]
@l4zy0n3 I have added another PR to hide the buggy chart. So changing to `To Test` column. 

- [ ] So we need to test if customers are not able to see the chart
