### ISSUE TITLE
Cert manager chart is missing

### ISSUE THREAD

**Issue by codejamninja** [rancher/charts#318]
Where did the cert-manager chart go?

![2019-11-06-200110_grim](https://user-images.githubusercontent.com/6234038/68353802-4344c780-00d0-11ea-878d-fa02488a78a2.png)

![2019-11-06-200056_grim](https://user-images.githubusercontent.com/6234038/68353807-463fb800-00d0-11ea-8165-d1c5d4d4e02e.png)

**Comment by codejamninja** [comment]
![2019-11-06-211610_grim](https://user-images.githubusercontent.com/6234038/68357351-ab98a680-00da-11ea-9f88-726156d3c647.png)

**Comment by codejamninja** [comment]
Rancher: v2.3.2
User Interface: v2.3.22
Helm: v2.14.3-rancher1
Machine: v0.15.0-rancher12-1

**Comment by codejamninja** [comment]
https://forums.rancher.com/t/cert-manager-chart-is-missing/15758

**Comment by pgporada** [comment]
Hi @codejamninja, I believe you need to see this Rancher forum post. https://forums.rancher.com/t/update-on-cert-manager-application-in-the-catalog/15598

**Comment by codejamninja** [comment]
Ok, thanks
