### ISSUE TITLE
More detailed documentation available?

### ISSUE THREAD

**Issue by Rancheroo** [rancher/charts#334]
The docs here: https://rancher.com/docs/rancher/v2.x/en/catalog/custom/creating/#question-variable-reference list variable types. Are the docs missing any types? I suspect so, because I see the type "pvc" in several questions.yaml files. 

Is there any more detailed technical documentation available?

Thank you

**Comment by guangbochen** [comment]
Yes, you are correct about some variable types are missing in the current doc of the `questions.yml`, will make a PR to update this, thanks for the report.

And for those missing variable types that we are supporting are:
```
pvc # persistent volume claim filtered by namespace
secret  # secret filtered by namespace
multiline # multiline string
```

**Comment by junkiebev** [comment]
@guangbochen - 
1) Can the *Multiline* type provide a yaml snippet (to populate a config map w/ or whatever), or is it just a string with *\n* characters?
2) Is a *Secret* type conditionally project-scoped instead of namespace-scoped?

**Comment by guangbochen** [comment]
@junkiebev 
1. multiline is a just string with `\n` characters and using `Edit as YAML` option would be the best way to add your yaml snippet.
2. secret type is namespace-scoped, project-scope is also making sense, will discuss with our engineers, thanks.
