### ISSUE TITLE
Kubeflow chart ml-pipeline Crashloops

### ISSUE THREAD

**Issue by tlfjar** [rancher/charts#354]
I am currently trying to get Kubeflow up and running from the experimental chart.  Everything deploys fine (though I cannot get it to deploy at all with persistent storage...issue for another day), except for the ml-pipeline component.  

The logs (labelled ml-pipeline-api-server) read as follows:

> I1231 20:32:37.113825 6 client_manager.go:123] Initializing client manager
[mysql] 2019/12/31 20:32:39 packets.go:427: busy buffer
[mysql] 2019/12/31 20:32:39 packets.go:408: busy buffer
E1231 20:32:39.256997 6 default_experiment_store.go:73] Failed to commit transaction to initialize default experiment table
[mysql] 2019/12/31 20:32:40 packets.go:427: busy buffer
[mysql] 2019/12/31 20:32:40 packets.go:408: busy buffer
E1231 20:32:40.263722 6 db_status_store.go:71] Failed to commit transaction to initialize database status table
[mysql] 2019/12/31 20:32:41 packets.go:427: busy buffer
[mysql] 2019/12/31 20:32:41 packets.go:408: busy buffer
E1231 20:32:41.268207 6 default_experiment_store.go:73] Failed to commit transaction to initialize default experiment table
F1231 20:32:41.273773 6 client_manager.go:291] Failed to create Minio bucket. Error: The request signature we calculated does not match the signature you provided. Check your key and signing method.
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc00035a500, 0xc00050e000, 0xcd, 0x1cd)
external/com_github_golang_glog/glog.go:769 +0xd4
github.com/golang/glog.(*loggingT).output(0x295a520, 0xc000000003, 0xc000416fd0, 0x283a7fc, 0x11, 0x123, 0x0)
external/com_github_golang_glog/glog.go:720 +0x329
github.com/golang/glog.(*loggingT).printf(0x295a520, 0xc000000003, 0x1aab81c, 0x28, 0xc0008b1b00, 0x1, 0x1)
external/com_github_golang_glog/glog.go:655 +0x14b
github.com/golang/glog.Fatalf(0x1aab81c, 0x28, 0xc0008b1b00, 0x1, 0x1)
external/com_github_golang_glog/glog.go:1148 +0x67
main.createMinioBucket(0xc0000eab40, 0xc0002df740, 0xa)
backend/src/apiserver/client_manager.go:291 +0x221
main.initMinioClient(0x53d1ac1000, 0x15, 0x53d1ac1000)
backend/src/apiserver/client_manager.go:277 +0x1e5
main.(*ClientManager).init(0xc0008b1cd8)
backend/src/apiserver/client_manager.go:140 +0x3de
main.newClientManager(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
backend/src/apiserver/client_manager.go:300 +0x7b
main.main()
backend/src/apiserver/main.go:56 +0x5e

**Comment by DavidSpek** [comment]
I believe I had a similar issue when deploying kubeflow 1.0.2 using kfctl, it was the ML-viewer if I remember correctly. To fix this issue I needed to upgrade my kernel. Kernel 5.5+ is supported, 5.4.2+ as well I believe and 5.3.x (can't remember which number x is, so not all versions). The supported kernels were reporting somewhere at the very top of the logs.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
