### ISSUE TITLE
Longhorn chart update

### ISSUE THREAD

**Issue by yasker** [rancher/charts#390]
1. Remove the experimental tag
2. Move Longhorn from proposed to charts , and ensure upgrade is still fine

**Comment by deniseschannon** [comment]
@yasker as of what Rancher version and longhorn version would experimental be removed?

**Comment by yasker** [comment]
@deniseschannon Rancher v2.3+ and Longhorn v0.7.0+ . It's ok if there is no rancher requirement for the tag. If that's the case, just need to remove the `experimental` tag for Longhorn v0.7.0+
