### ISSUE TITLE
Add existingClaim option for the available charts

### ISSUE THREAD

**Issue by yasker** [rancher/charts#47]
Almost every chart uses persistent volume supports using existing PVCs. But the option was disabled by `questions.yaml`. This option is needed if the user wants to persist the volume content beyond the lifecycle of the app.

We need something similar to https://github.com/rancher/charts/pull/41/commits for all the charts which support persistent volume.

If we can enable the user to choose which PVC they want in the current namespace it would be even better.

**Comment by guangbochen** [comment]
Version: master 2.2 (1/4/19)
Confirmed new feature. See https://github.com/rancher/rancher/issues/17060 for details. This was tested in the UI and confirmed working.
