### ISSUE TITLE
Datadog - `ranchercharts/agent:7` does not exist

### ISSUE THREAD

**Issue by kingsd041** [rancher/charts#473]
The image specified in https://github.com/rancher/charts/blob/master/charts/datadog/v2.1.2/values.yaml#L868-L874 is `ranchercharts/agent:7`, but this image does not exist
```
root@rancher2:~# docker pull ranchercharts/agent:7
Error response from daemon: pull access denied for ranchercharts/agent, repository does not exist or may require 'docker login'

```
Should it be `ranchercharts/datadog-agent:7`?

gz#11786

**Comment by guangbochen** [comment]
@kingsd041 this is correct, as a workaround, the user can modify it use a `custom image` and u can also make a pull request to fix it, thanks.

**Comment by axeal** [comment]
@guangbochen In the questions.yaml we set a default of `ranchercharts/datadog-agent` for `clusterChecksRunner.image.repository` (https://github.com/rancher/charts/blob/master/charts/datadog/v2.1.2/questions.yml#L35), but in the values.yaml this is left as a default of `ranchercharts/agent` (https://github.com/rancher/charts/blob/master/charts/datadog/v2.1.2/values.yaml#L868). Seems like we should update the default in the values.yaml to `ranchercharts/datadog-agent` also, so it is correct as the other agent images in values.yaml are.

**Comment by guangbochen** [comment]
yep, and both image repo will have the image that is needed to for this chart, previously we trying to sync catalog image s to the `ranchercharts` repo to get the analytics data of catalog apps, however, this is no longer maintained so we may leave this version as what it is, for the next version they will be using the origin image repo instead, thanks.
