### ISSUE TITLE
[charts/datadog] error setting datadog.podLabelsAsTags

### ISSUE THREAD

**Issue by aleixrm-scopely** [rancher/charts#476]
I'm having an issue setting the datadog.podLabelsAsTags answer value for the datadog chart v2.1.2. If I set the label json map as is shown in the example, e.g.

`{"app":"kube_app","cluster":"kube_cluster","stack":"kube_stack","detail":"kube_detail"}`

 the datadog agent is not able to retrieve the json as a label map, appearing the following error when viper tries to load the environment variable content (log extracted from the datadog-agent container):

```
CORE | WARN | (pkg/config/viper.go:190 in GetStringMapString) | failed to get configuration value for key "kubernetes_pod_labels_as_tags": json: cannot unmarshal array into Go value of type map[string]string
```

I've checked the datadog-agent daemon set, and the generated content is:
```
        - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
          value: '["\"app\":\"kube_app\"","\"cluster\":\"kube_cluster\"","\"stack\":\"kube_stack\"","\"detail\":\"kube_detail\""]'
```

This is because, as the rancher documentation says, the answers are set into the helm chart with the --set parameter, in order to override de values.yaml configuration. The --set parameter for helm has some limitation: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set, so following the example in the questions.yaml for this field, it seems that the json is interpreted as a values list when set in the --set argument of the helm install/upgrade.

I've tried to escape the brackets, then the following environment variable string is generated on the yaml:
```
        - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
          value: '"{\"app\":\"kube_app\",\"cluster\":\"kube_cluster\",\"stack\":\"kube_stack\",\"detail\":\"kube_detail\"}"'
```
but this still fails to be parsed by viper in the datadog-agent container of the daemonset:
```
pkg/config/viper.go:190 in GetStringMapString) | failed to get configuration value for key "kubernetes_pod_labels_as_tags": json: cannot unmarshal string into Go value of type map[string]string
```

I've tried more escaped characters combinations, but none of them succeeded. I've downloaded the chart locally and changed the container-agent.yaml template, removing the toJson function from the DD_KUBERNETES_POD_LABELS_AS_TAGS environment variable (https://github.com/rancher/charts/blob/master/charts/datadog/v2.1.2/templates/container-agent.yaml#L78) and then setting the datadog.podLabelsAsTags parameter with --set in the following format when calling the helm template command:
```
--set datadog.podLabelsAsTags='\{"app":"kube_app"\,"cluster":"kube_cluster"\,"stack":"kube_stack"\,"detail":"kube_detail"\}'
```
it seems that generated the correct DD_KUBERNETES_POD_LABELS_AS_TAGS field in the manifest:
```
            - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
              value: '{"app":"kube_app","cluster":"kube_cluster","stack":"kube_stack","detail":"kube_detail"}'
```

I don't know which is the proper solution for that, maybe I haven't found the proper format for setting a json as a value override using the --set argument (in that case, the example provided in the helm char answer.yaml should be changed), or the "toJson" function should be removed from the helm template in container-agent.yaml file in order to allow us properly escape the datadog.podLabelsAsTags answer. This issue also should occur with the datadog.podAnnotationsAsTags and datadog.nodeLabelsAsTags answer values.

**Comment by aleixrm-scopely** [comment]
Possible related issue: https://github.com/helm/helm/issues/5618

**Comment by rogersd** [comment]
I'm having the exact same problem.  The sample JSON given on the form field doesn't even work.

**Comment by deniseschannon** [comment]
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.
