### ISSUE TITLE
Tags feature

### ISSUE THREAD

**Issue by KuroObi** [rancher/charts#49]
Hey,

I'm not sure if this is the right place to ask.
But is there a way to ad a custom tag to a custom helm Chart from a private repository like for example (question.yml):
```
labels:
  io.rancher.certified: <Company Name>
```
This feature worked in rancher v1 cattle catalog and help our team a lot. Is this gona be available in the helm charts too?

**Comment by guangbochen** [comment]
yes, and `questions.yml` is the right place to add.
