### ISSUE TITLE
drone template error 

### ISSUE THREAD

**Issue by kgk** [rancher/charts#54]
[tiller] 2018/10/26 16:46:23 failed install prepare step: YAML parse error on drone/templates/deployment-server.yaml: error converting YAML to JSON: yaml: line 29: could not find expected ':'
2018/10/26 16:46:23 [ERROR] AppController p-b86j6/drone [helm-controller] failed with : failed to install app drone. Error: YAML parse error on drone/templates/deployment-server.yaml: error converting YAML to JSON: yaml: line 29: could not find expected ':'

Trying with bitbucket OAth.. local install of drone works with same OAuth token.

**Comment by Ilshidur** [comment]
Same exact error when trying with GitLab.

**Comment by xRoker** [comment]
After the recent update I'm experiencing a similar problem with GitHub:
Failed to install app drone-dvcng. Error: UPGRADE FAILED: YAML parse error on drone/templates/deployment-server.yaml: error converting YAML to JSON: yaml: line 27: found character that cannot start any token

**Comment by guangbochen** [comment]
@xRoker thanks for the report and it was resolved, please refresh the catalog before installing the latest version of Drone.

**Comment by KaelBaldwin** [comment]
I tried upgrading to the latest version of drone:

![image](https://user-images.githubusercontent.com/13858623/50356531-ebcd5580-0517-11e9-8ac8-544612d9344c.png)

is the first issue.

So I switched to edit it as yaml, wanting to preserve my PVC and still upgrade to a newer drone. I set it this way:

`persistence.existingClaim: drone-drone`

however when I ran the upgrade, it deleted my PVC. Sad day.

**Comment by KaelBaldwin** [comment]
luckily it really just amounts to losing drone secrets, so it could be worse.

**Comment by KaelBaldwin** [comment]
@guangbochen 

My mistake was using the new existingClaim field to try to carry over my 1.4.0 chart created PVC.

Doing so made the chart no longer responsible for any PVC so it removed the one it created before, which incidentally had the same name as the existingClaim.

May or may not be room for improvement in the chart to prevent the above scenario from happening to anyone else, not sure.

**Comment by guangbochen** [comment]
close as this issue is resolved.
