### ISSUE TITLE
Upgrade NodePort to Rancher Proxy result in failure

### ISSUE THREAD

**Issue by yasker** [rancher/charts#71]
Error message:
```
Installing
Failed to install app longhorn. Error: UPGRADE FAILED: Service "longhorn-frontend" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

Not sure it's Longhorn specific or a general issue.

**Comment by guangbochen** [comment]
this is a common behavior of k8s, user can edit the service yaml file directly with followig changes :
```
type: NodePort -> ClusterIP
nodePort: 32000 -> # remove this line 
```

**Comment by yasker** [comment]
Is there any way for the Rancher or Helm automatically deal with it? The user is using Helm and k8s through Rancher.

**Comment by guangbochen** [comment]
helm upgrade or kubectl apply with `--force` can address the can't upgrade immutable fields issue, will create a new feature request in Rancher.

**Comment by guangbochen** [comment]
close as it will be addressed in rancher/rancher https://github.com/rancher/rancher/issues/16769
