### ISSUE TITLE
Application Artifactory-Ha does not show any Endpoint in Rancher 2.1.2

### ISSUE THREAD

**Issue by luigidifraia** [rancher/charts#74]
Application: Artifactory-Ha
Template Version: 0.7.6
Expose app using Layer 7 Load Balancer: Yes
Hostname: Automatically generate a .xip.io hostname
Enable Persistent Storage for Artifactory: False

Issue: No Endpoints show in Rancher's UI for the application. However an ingress rule, artifactory-ha, does. The endpoint is present, working, and showing within the ingress rule's YAML: artifactory-ha.artifactory-ha.x.y.w.z.xip.io

**Comment by guangbochen** [comment]
the endpoint may not be showing because your artifactory app is not running, and it is because you have turned off the PVc, close in favor of #75, please feel free to reopen it if can't address this issue after fixing #75.

**Comment by luigidifraia** [comment]
This bug is not related to the one about Artifactory-HA not running. This bug refers to a running instance with fulfilled/bound PVC. As I mentioned in the description "The endpoint is present, working, and showing within the ingress rule's YAML".
