### ISSUE TITLE
rancher-charts/rancher-backup chart broken

### ISSUE THREAD

**Issue by travis-sobeck** [rancher/charts#801]
ran the following
````
    helm repo add rancher-charts https://charts.rancher.io
    helm repo update
    helm install rancher-backup-crd rancher-charts/rancher-backup-crd -n cattle-resources-system --create-namespace
    helm install rancher-backup rancher-charts/rancher-backup -n cattle-resources-system
````
and get the following 
`Release "rancher-backup" does not exist. Installing it now.
Error: parse error at (rancher-backup/templates/validate-install-crd.yaml:1): function "lookup" not defined`

**Comment by travis-sobeck** [comment]
I downloaded the chart and deleted the contests of rancher-backup/templates/validate-install-crd.yaml and I can get that to work, but seems a bit odd to have to do all that

**Comment by mrajashree** [comment]
@travis-sobeck which Helm version are you on? For 2.5.x as per docs it should be [3.2.x and up](https://rancher.com/docs/rancher/v2.x/en/installation/resources/helm-version/)

**Comment by travis-sobeck** [comment]
@mrajashree 
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
I will update my helm this afternoon and re-test.
Thanks

**Comment by travis-sobeck** [comment]
@mrajashree 
After updating helm I was able to install normally without an issue.
Thanks!
after running 'helm install rancher-backup-crd rancher-charts/rancher-backup-crd -n cattle-resources-system' I did get a warning, just an FYI not an issue
```
W1112 13:59:35.677366   12412 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```
