### ISSUE TITLE
The changes leading up to artifactory-ha 0.7.12 were merged into the 0.7.6 folder

### ISSUE THREAD

**Issue by luigidifraia** [rancher/charts#85]
As per title, was it an accidental merge? It looks like the chart version 0.7.6 was uplifted to version 0.7.12 in place, instead of ending up in a separate folder.

**Comment by jainishshah17** [comment]
@luigidifraia You are right. It's mistake.

**Comment by jainishshah17** [comment]
@luigidifraia I took another look at the chart. It is correct. We have added new version `0.7.12` under latest and moved `0.7.6` under a separate directory.

**Comment by luigidifraia** [comment]
@jainishshah17 I see. The folder `latest` was moved to `0.7.6` as part of the commit with description "Moving into artifactory-ha v.0.7.12/6.5.9 (#80)".
For clarity, I'd recommend separate commits and a single push in future.
