### ISSUE TITLE
rancher-monitoring chart missing AlertmanagerConfig crd

### ISSUE THREAD

**Issue by alpha01** [rancher/charts#871]
Hello,

Is their a plan to add AlertmanagerConfig (alertmanagerconfigs.monitoring.coreos.com) crd to the rancher-monitoring chart? This seems to be a better approach than the current v2.5 of having to modify the secret alertmanager-rancher-monitoring-alertmanager.
    
Also having this crd available will make it easier to implement Alertmanager multi-instances for multi-tenant cluster environments while still leveraging the use of rancher-monitoring. 

gz#15721

**Comment by wangxf1987** [comment]
hi, I occur this issue, Did your solve the ploblem?

**Comment by Tejeev** [comment]
@aiyengar2 I'm not sure if you were working on this but just FYI that this issue exists and may need to be merged with any issue being used to track the upgrade of the Prometheus charts.

Do we know what we will upgrade to?
The request I've had internally is for an update Prometheus Operators in rancher-monitoring to release 0.46.0

**Comment by aiyengar2** [comment]
@alpha01 yes, the plan is to introduce that CRD as part of https://github.com/rancher/rancher/issues/29871. I'm closing out this issue in favor of that issue.

@Tejeev the upgrade will also be prioritized along with https://github.com/rancher/rancher/issues/29871, which is up to date with 0.46.0 https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/kube-prometheus-stack/values.yaml#L1483
